spring:
  cloud:
    gateway:
      routes:
        - id: customers-route
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
        - id: InventoryService
          uri: http://localhost:8082
          predicates:
            - Path=/products/**
    management:
      endpoints:
        web:
          exposure:
            include: gateway
